const Movies = [
  {
    id: 1,
    title: "Inception",
    year: 2010,
    rating: 8.8,
    duration: "2h 28m",
    mood: "Mind-Bending",
    genres: ["Sci-Fi", "Action"],
    image: "https://source.unsplash.com/random/300x450/?inception,movie",
    liked: false,
  },
  {
    id: 2,
    title: "The Shawshank Redemption",
    year: 1994,
    rating: 9.3,
    duration: "2h 22m",
    mood: "Inspirational",
    genres: ["Drama"],
    image: "https://source.unsplash.com/random/300x450/?shawshank,redemption",
    liked: false,
  },
  {
    id: 3,
    title: "Pulp Fiction",
    year: 1994,
    rating: 8.9,
    duration: "2h 34m",
    mood: "Gritty",
    genres: ["Crime", "Thriller"],
    image: "https://source.unsplash.com/random/300x450/?pulp,fiction",
    liked: false,
  },
  {
    id: 4,
    title: "The Dark Knight",
    year: 2008,
    rating: 9.0,
    duration: "2h 32m",
    mood: "Intense",
    genres: ["Action", "Thriller"],
    image: "https://source.unsplash.com/random/300x450/?dark,knight",
    liked: false,
  },
  {
    id: 5,
    title: "Parasite",
    year: 2019,
    rating: 8.6,
    duration: "2h 12m",
    mood: "Dark Comedy",
    genres: ["Thriller", "Drama"],
    image: "https://source.unsplash.com/random/300x450/?parasite,movie",
    liked: false,
  },
  {
    id: 6,
    title: "Spirited Away",
    year: 2001,
    rating: 8.6,
    duration: "2h 5m",
    mood: "Whimsical",
    genres: ["Animation", "Fantasy"],
    image: "https://source.unsplash.com/random/300x450/?spirited,away",
    liked: false,
  },
  {
    id: 7,
    title: "The Grand Budapest Hotel",
    year: 2014,
    rating: 8.1,
    duration: "1h 39m",
    mood: "Quirky",
    genres: ["Comedy", "Adventure"],
    image: "https://source.unsplash.com/random/300x450/?grand,budapest",
    liked: false,
  },
  {
    id: 8,
    title: "Interstellar",
    year: 2014,
    rating: 8.6,
    duration: "2h 49m",
    mood: "Epic",
    genres: ["Sci-Fi", "Adventure"],
    image: "https://source.unsplash.com/random/300x450/?interstellar,space",
    liked: false,
  },
  {
    id: 9,
    title: "Get Out",
    year: 2017,
    rating: 7.7,
    duration: "1h 44m",
    mood: "Suspenseful",
    genres: ["Horror", "Thriller"],
    image: "https://source.unsplash.com/random/300x450/?get,out,movie",
    liked: false,
  },
  {
    id: 10,
    title: "La La Land",
    year: 2016,
    rating: 8.0,
    duration: "2h 8m",
    mood: "Romantic",
    genres: ["Musical", "Drama"],
    image: "https://source.unsplash.com/random/300x450/?lalaland,musical",
    liked: false,
  },
];

export default Movies;